INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:10] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:46] "[32mGET /api/v1.0 HTTP/1.1[0m" 308 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:46] "[35m[1mGET /api/v1.0/ HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:46] "[37mGET /api/v1.0/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:46] "[37mGET /api/v1.0/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:46] "[37mGET /api/v1.0/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:46] "[37mGET /api/v1.0/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:02:46] "[37mGET /api/v1.0/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/home/alex/alexPrograms/FlaskShop/ishop/api_1_0/demo.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
INFO _internal.py:113  * Detected change in '/home/alex/alexPrograms/FlaskShop/ishop/api_1_0/demo.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
INFO _internal.py:113  * Detected change in '/home/alex/alexPrograms/FlaskShop/ishop/api_1_0/demo.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
ERROR demo.py:10 error
WARNING demo.py:11 warn
INFO demo.py:12 info
DEBUG demo.py:13 debug
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:05:03] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [28/Aug/2020 23:05:03] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Detected change in '/home/alex/alexPrograms/FlaskShop/ishop/api_1_0/demo.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
INFO _internal.py:113  * Detected change in '/home/alex/alexPrograms/FlaskShop/ishop/api_1_0/demo.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
INFO _internal.py:113  * Detected change in '/home/alex/alexPrograms/FlaskShop/ishop/__init__.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
INFO _internal.py:113  * Detected change in '/home/alex/alexPrograms/FlaskShop/ishop/__init__.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
ERROR demo.py:10 error
WARNING demo.py:11 warning
INFO demo.py:12 info
DEBUG demo.py:13 debug
ERROR demo.py:14 error
WARNING demo.py:15 warn
INFO demo.py:16 info
DEBUG demo.py:17 debug
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 09:54:34] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 09:54:34] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR demo.py:10 error
WARNING demo.py:11 warning
INFO demo.py:12 info
DEBUG demo.py:13 debug
ERROR demo.py:14 error
WARNING demo.py:15 warn
INFO demo.py:16 info
DEBUG demo.py:17 debug
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:21:48] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:21:48] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR demo.py:10 error
WARNING demo.py:11 warning
INFO demo.py:12 info
DEBUG demo.py:13 debug
ERROR demo.py:14 error
WARNING demo.py:15 warn
INFO demo.py:16 info
DEBUG demo.py:17 debug
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:21:51] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:21:51] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR demo.py:10 error
WARNING demo.py:11 warning
INFO demo.py:12 info
DEBUG demo.py:13 debug
ERROR demo.py:14 error
WARNING demo.py:15 warn
INFO demo.py:16 info
DEBUG demo.py:17 debug
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:21:52] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:21:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR demo.py:10 error
WARNING demo.py:11 warning
INFO demo.py:12 info
DEBUG demo.py:13 debug
ERROR demo.py:14 error
WARNING demo.py:15 warn
INFO demo.py:16 info
DEBUG demo.py:17 debug
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:21:52] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:21:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 258-541-989
ERROR demo.py:10 error
WARNING demo.py:11 warning
INFO demo.py:12 info
DEBUG demo.py:13 debug
ERROR demo.py:14 error
WARNING demo.py:15 warn
INFO demo.py:16 info
DEBUG demo.py:17 debug
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:22:05] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:22:05] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR demo.py:10 error
WARNING demo.py:11 warning
INFO demo.py:12 info
DEBUG demo.py:13 debug
ERROR demo.py:14 error
WARNING demo.py:15 warn
INFO demo.py:16 info
DEBUG demo.py:17 debug
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:22:06] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 21:22:06] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR demo.py:10 error
WARNING demo.py:11 warning
INFO demo.py:12 info
DEBUG demo.py:13 debug
ERROR demo.py:14 error
WARNING demo.py:15 warn
INFO demo.py:16 info
DEBUG demo.py:17 debug
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 23:26:12] "[37mGET /api/v1.0/ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [29/Aug/2020 23:26:12] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR __init__.py:98 Error: Directory migrations already exists and is not empty
ERROR __init__.py:98 Error: Directory migrations already exists and is not empty
